apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-boutique-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend  # Adjust this to match your service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s